name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.SAMPLEAPP_ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.SAMPLEAPP_ACR_PASSWORD }}
        # Container registry server url
        login-server: itlfinancecr.azurecr.us
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:         
        docker build . --file WebApp.Dockerfile --tag itlfinancecr.azurecr.us/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag itlfinancecr.azurecr.us/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER itlfinancecr.azurecr.us/sample-app-aoai-chatgpt:latest;
        docker push itlfinancecr.azurecr.us/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push itlfinancecr.azurecr.us/sample-app-aoai-chatgpt:latest;
      
